spring:
  config:
    import: classpath:/mail-dev.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animalshelter
    username: root
    password: xxx
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml