spring:
  datasource-catalogue:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/shelter-catalogue
    username: root
    password: root
  datasource-proposal:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3308/shelter-proposal
    username: root
    password: root