spring:
  datasource-catalogue:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/shelter-catalogue
    username: root
    password: root
    liquibase:
      change-log: classpath:db/changelog/catalogue/db.changelog-catalogue-master.xml
  datasource-adoption:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3308/shelter-proposal
    username: root
    password: root
    liquibase:
      change-log: classpath:db/changelog/proposal/db.changelog-proposal-master.xml