spring:
  datasource-catalogue:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:catalogue-test-db
    username: sa
    password:
  datasource-adoption:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:proposal-test-db
    username: sa
    password: